---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gitops-foundations-env-2892009
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://https://github.com/amanpurwar1/gitops-foundations-env-2892009

