Flag --validation has been deprecated, this arg is no longer used, all resources are validated using server-side apply dry-run
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitops-foundations-env-2892009
  namespace: flux-system
spec:
  interval: 1m
  path: ./flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-foundations-env-2892009

